# Generated by Django 2.0.4 on 2018-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entity_app', '0001_initial'),
        ('firewall_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedestination',
            name='dst_geoip_country_list',
        ),
        migrations.AddField(
            model_name='sourcedestination',
            name='dst_geoip_country_list',
            field=models.ManyToManyField(blank=True, related_name='_sourcedestination_dst_geoip_country_list_+',
                                         to='entity_app.Address'),
        ),
        migrations.RemoveField(
            model_name='sourcedestination',
            name='src_geoip_country_list',
        ),
        migrations.AddField(
            model_name='sourcedestination',
            name='src_geoip_country_list',
            field=models.ManyToManyField(blank=True, related_name='_sourcedestination_src_geoip_country_list_+',
                                         to='entity_app.Address'),
        ),
    ]
