# Generated by Django 2.0.4 on 2018-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_app', '0002_auto_20180417_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedestination',
            name='dst_geoip_country_list',
            field=models.ManyToManyField(blank=True, related_name='_sourcedestination_dst_geoip_country_list_+',
                                         to='entity_app.CountryCode'),
        ),
        migrations.AlterField(
            model_name='sourcedestination',
            name='src_geoip_country_list',
            field=models.ManyToManyField(blank=True, related_name='_sourcedestination_src_geoip_country_list_+',
                                         to='entity_app.CountryCode'),
        ),
    ]
