# Generated by Django 2.0.4 on 2018-04-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entity_app', '0003_auto_20180422_0535'),
        ('firewall_app', '0003_auto_20180417_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedestination',
            name='application_list',
            field=models.ManyToManyField(blank=True, related_name='_sourcedestination_application_list_+',
                                         to='entity_app.Application'),
        ),
    ]
