# Generated by Django 2.0.6 on 2018-07-04 13:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_app', '0005_remove_sourcedestination_application_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCommandsForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_chains',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='chain_commands')),
                ('chain_commands',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='chain_commands')),
                ('main_rule_commands',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='chain_commands')),
                ('nat_rule_commands',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='chain_commands')),
                ('pbr_commands',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='chain_commands')),
                ('main_order', models.IntegerField(default=0, null=True)),
                ('nat_order', models.IntegerField(default=0, null=True)),
                ('policy_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
