# Generated by Django 2.1 on 2018-08-14 07:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_app', '0006_policycommandsfortest'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycommandsfortest',
            name='dst_ip_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='dst_ip_list'),
        ),
        migrations.AddField(
            model_name='policycommandsfortest',
            name='src_ip_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='src_ip_list'),
        ),
    ]
