# Generated by Django 2.1 on 2018-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0008_change_policy_name_max_length_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Name'),
        ),
    ]
