# Generated by Django 2.1 on 2018-11-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0009_auto_20180828_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='QOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('download_max_bw', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max_bandwidth')),
                ('download_guaranteed_bw', models.PositiveIntegerField(blank=True, null=True, verbose_name='Guaranteed_bandwidth')),
                ('download_traffic_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20, verbose_name='Priority')),
                ('download_shape_type', models.CharField(choices=[('Per-IP', 'Per-IP'), ('Per-Session', 'Per-Session')], default='per-session', max_length=20, verbose_name='Type')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='qos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firewall_app.QOS', verbose_name='QOS'),
        ),
    ]
