# Generated by Django 2.1 on 2018-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0010_auto_20181112_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qos',
            name='download_shape_type',
            field=models.CharField(choices=[('per-ip', 'Per-IP'), ('per-session', 'Per-Session')], default='per-session', max_length=20, verbose_name='Type'),
        ),
    ]
