# Generated by Django 2.1 on 2018-11-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0011_auto_20181113_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qos',
            name='download_shape_type',
            field=models.CharField(choices=[('per_ip', 'Per_IP'), ('per_session', 'Per_Session')], default='per_session', max_length=20, verbose_name='Type'),
        ),
    ]
