# Generated by Django 2.1 on 2018-11-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0012_auto_20181113_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='action',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Action'),
        ),
    ]
