# Generated by Django 2.1 on 2018-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0013_auto_20181113_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='qos',
            name='class_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='class_id'),
        ),
        migrations.AlterField(
            model_name='qos',
            name='download_traffic_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='Priority'),
        ),
    ]
