# Generated by Django 2.1 on 2018-11-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0014_auto_20181126_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qos',
            name='is_enabled',
        ),
    ]
