# Generated by Django 2.1 on 2018-11-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0015_remove_qos_is_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qos',
            old_name='download_shape_type',
            new_name='shape_type',
        ),
        migrations.RenameField(
            model_name='qos',
            old_name='download_traffic_priority',
            new_name='traffic_priority',
        ),
    ]
