# Generated by Django 2.1.3 on 2019-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_app', '0016_auto_20181128_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='qos',
            name='status',
            field=models.CharField(blank=True,
                                   choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded'),
                                            ('disabled', 'disabled')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
