# Generated by Django 2.1 on 2018-08-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstime',
            name='profile_access_enabled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Access status'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='exceeded_quota_active',
            field=models.BooleanField(blank=True, default=False, help_text='Active Exceeded Quota',
                                      verbose_name='Active Exceeded Quota'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='notification_enabled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Notify User,Group(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='force_logout',
            field=models.BooleanField(blank=True, default=False, help_text='Logged out users immediatly',
                                      verbose_name='Apply changes immediately'),
        ),
        migrations.AlterField(
            model_name='usermac',
            name='force_mac_auth',
            field=models.BooleanField(blank=True, default=False, verbose_name='MAC binding'),
        ),
    ]
