# Generated by Django 2.1.3 on 2019-02-20 18:06

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[
                    django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$',
                                                          'Only alphanumeric characters are allowed.')],
                                          verbose_name='Name')),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                    choices=[('ping', 'Ping'), ('mtr', 'Mtr'), ('conntrack', 'Conntrack'), ('ram_cpu', 'RAM & CPU')],
                    max_length=10), size=None)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration')),
                ('remote_endpoint_report',
                 models.GenericIPAddressField(blank=True, null=True, verbose_name='Remote Endpoint')),
                ('local_host_report', models.GenericIPAddressField(blank=True, null=True, verbose_name='Local Host')),
                ('remote_host_report', models.GenericIPAddressField(blank=True, null=True, verbose_name='Remote Host')),
                (
                    'result',
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Result')),
                (
                    'last_operation',
                    models.CharField(blank=True, max_length=7, null=True, verbose_name='Last Operation')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('failed', 'failed'),
                                                                 ('succeeded', 'succeeded'), ('disabled', 'disabled'),
                                                                 ('stopped', 'stopped')], max_length=20, null=True,
                                            verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Diagnosis Report',
                'verbose_name_plural': 'Diagnosis Reports',
            },
        ),
    ]
