# Generated by Django 2.1 on 2018-08-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminloginlock',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
