# Generated by Django 2.0.4 on 2018-04-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_list', models.ManyToManyField(blank=True, related_name='_dnsinterface_interface_list_+',
                                                          to='config_app.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipAddress')),
                ('host_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hostname')),
            ],
        ),
        migrations.CreateModel(
            name='DNSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_dns_server', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipAddress')),
                ('secondary_dns_server', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipAddress')),
                ('tertiary_dns_server', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipAddress')),
                ('local_domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='local_domain')),
            ],
        ),
    ]
