# Generated by Django 2.0.4 on 2018-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_dnsinterface_dnsrecord_dnsserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsinterface',
            name='interface_list',
        ),
        migrations.AddField(
            model_name='dnsserver',
            name='interface_list',
            field=models.ManyToManyField(blank=True, related_name='_dnsserver_interface_list_+', to='config_app.Interface'),
        ),
        migrations.DeleteModel(
            name='DNSInterface',
        ),
    ]
