# Generated by Django 2.0.4 on 2018-04-17 13:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0004_auto_20180417_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsrecord',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dnsrecord',
            name='host_name',
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='host_name_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='host_name_list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='ip_address',
            field=models.GenericIPAddressField(default='4.2.2.4', verbose_name='ip_address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='primary_dns_server',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='primary_dns_server'),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='secondary_dns_server',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='secondary_dns_server'),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='tertiary_dns_server',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='tertiary_dns_server'),
        ),
    ]
