# Generated by Django 2.0.4 on 2018-04-18 10:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0005_auto_20180417_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsrecord',
            name='host_name_list',
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='hostname_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='hostname_list'),
            preserve_default=False,
        ),
    ]
