# Generated by Django 2.0.4 on 2018-04-22 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0006_auto_20180418_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='dns_server_list',
        ),
    ]
