# Generated by Django 2.0.4 on 2018-04-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0007_remove_interface_dns_server_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsconfig',
            name='last_operation',
            field=models.CharField(blank=True, choices=[('add', 'add'), ('update', 'update')], max_length=20, null=True,
                                   verbose_name='Last Operation'),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='status',
            field=models.CharField(blank=True,
                                   choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded')],
                                   max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='last_operation',
            field=models.CharField(blank=True, choices=[('add', 'add'), ('update', 'update'), ('delete', 'delete')],
                                   max_length=20, null=True, verbose_name='Last Operation'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='status',
            field=models.CharField(blank=True,
                                   choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded')],
                                   max_length=20, null=True, verbose_name='Status'),
        ),
    ]
