# Generated by Django 2.0.5 on 2018-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0008_auto_20180423_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
