# Generated by Django 2.0.5 on 2018-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0009_auto_20180512_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded')],
                                   default='succeeded', max_length=20, verbose_name='Status'),
        ),
    ]
