# Generated by Django 2.0.5 on 2018-05-28 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0011_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_app_token',
                                    to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
