# Generated by Django 2.0.5 on 2018-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0012_auto_20180528_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
