# Generated by Django 2.0.5 on 2018-05-30 07:05

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0013_auto_20180530_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminloginlock',
            name='datetime_created',
            field=models.DateField(auto_created=True,
                                   default=datetime.datetime(2018, 5, 30, 7, 5, 36, 95330, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
