# Generated by Django 2.0.6 on 2018-06-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0015_auto_20180531_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_secure', models.BooleanField(default=False, verbose_name='Is Secure')),
                ('CA_certificate', models.TextField(blank=True, null=True)),
                ('last_operation',
                 models.CharField(blank=True, choices=[('add', 'add'), ('update', 'update')], max_length=20, null=True,
                                  verbose_name='Last Operation')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('failed', 'failed'),
                                                                 ('succeeded', 'succeeded')], max_length=20, null=True,
                                            verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='SystemService',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(
                    choices=[('available', 'available'), ('downloading', 'downloading'), ('downloaded', 'downloaded'),
                             ('validating', 'validating'), ('validated', 'validated'), ('installing', 'installing'),
                             ('completed', 'completed')], default='available', max_length=20)),
                ('description', models.TextField()),
                ('server_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='logserver',
            name='is_secure',
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='is_strict_order',
            field=models.BooleanField(default=True, verbose_name='Is DNS servers in strict order'),
        ),
        migrations.AddField(
            model_name='setting',
            name='category',
            field=models.TextField(default='Other'),
        ),
        migrations.AddField(
            model_name='setting',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='type',
            field=models.CharField(blank=True, choices=[('number', 'number'), ('bool', 'bool'), ('string', 'string'),
                                                        ('certificate', 'certificate')], max_length=20, null=True,
                                   verbose_name='Type'),
        ),
    ]
