# Generated by Django 2.0.6 on 2018-07-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0016_auto_20180626_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='version',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
