# Generated by Django 2.0.6 on 2018-07-02 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0017_auto_20180701_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLoginLock',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
