# Generated by Django 2.0.6 on 2018-07-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0018_auto_20180702_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='status',
            field=models.CharField(
                choices=[('available', 'available'), ('downloading', 'downloading'), ('downloaded', 'downloaded'),
                         ('validating', 'validating'), ('validated', 'validated'), ('installing', 'installing'),
                         ('completed', 'completed'), ('failed', 'failed')], default='available', max_length=20),
        ),
    ]
