# Generated by Django 2.1 on 2018-08-06 07:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def remove_old_settings(apps, schema_editor):
    setting_model = apps.get_model('config_app', 'Setting')
    setting_model.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0020_interface_mac'),
    ]

    operations = [
        migrations.RunPython(remove_old_settings),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
