# Generated by Django 2.1 on 2018-08-06 09:43
from django.db import migrations



class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0021_auto_20180806_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='value',
            new_name='data',
        ),
    ]
