# Generated by Django 2.1 on 2018-09-05 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0023_remove_extra_general_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logserver',
            name='service_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vpn', 'vpn'), ('ssh', 'ssh'), ('firewall', 'firewall')], max_length=10), size=None),
        ),
    ]
