# Generated by Django 2.1 on 2018-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0025_change_logserver_policy_field_name_to_firewall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
