# Generated by Django 2.1 on 2018-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0026_auto_20180909_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='status',
            field=models.CharField(
                choices=[('available', 'available'), ('downloading', 'downloading'), ('downloaded', 'downloaded'),
                         ('validating', 'validating'), ('validated', 'validated'), ('restore_point', 'restore_point'),
                         ('installing', 'installing'), ('completed', 'completed'), ('rollback', 'rollback'),
                         ('failed', 'failed')], default='available', max_length=20),
        ),
    ]
