# Generated by Django 2.1 on 2018-09-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0027_auto_20180925_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='install_progress',
            field=models.IntegerField(default=100),
        ),
    ]
