# Generated by Django 2.1 on 2018-10-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0028_update_install_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='update_log_flag',
            field=models.BooleanField(default=0),
        ),
    ]
