# Generated by Django 2.1 on 2018-10-10 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0030_auto_20181010_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_operation', models.CharField(blank=True, choices=[('add', 'add'), ('update', 'update')], max_length=20, null=True, verbose_name='Last Operation')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded')], max_length=20, null=True, verbose_name='Status')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('snmp_type', models.CharField(default='v3', max_length=20, verbose_name='SNMP Type')),
                ('community_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Community Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is_Enable')),
                ('allow_network', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='Allow Network')),
                ('user_name', models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$', 'Only alphanumeric characters are allowed.')], verbose_name='User Name')),
                ('security_level', models.CharField(blank=True, choices=[('noauth', 'No Autentication,No Encryption'), ('auth', 'Autentication No Encryption '), ('priv', 'Authnetication Encryption ')], max_length=30, null=True, verbose_name='Security Level')),
                ('private_algorithm', models.CharField(blank=True, choices=[('des', 'DES'), ('aes', 'AES')], max_length=20, null=True, verbose_name='Encryption Algorithm')),
                ('authentication_algorithm', models.CharField(blank=True, choices=[('md5', 'MD5'), ('sha', 'SHA')], max_length=20, null=True, verbose_name='Authentication Algorithm')),
                ('authentication_passowrd', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Authentication Password')),
                ('private_password', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Private Password')),
            ],
        ),
    ]
