# Generated by Django 2.1 on 2018-10-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0031_snmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_log_flag',
            field=models.NullBooleanField(default=0),
        ),
    ]
