# Generated by Django 2.1 on 2018-10-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0032_auto_20181013_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snmp',
            old_name='authentication_passowrd',
            new_name='authentication_password',
        ),
    ]
