# Generated by Django 2.1 on 2018-10-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0033_auto_20181021_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='download_bandwidth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Download bandwidth'),
        ),
        migrations.AddField(
            model_name='interface',
            name='upload_bandwidth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Upload bandwidth'),
        ),
    ]
