# Generated by Django 2.1.3 on 2018-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0034_auto_20181021_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='qos_status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded'), ('disabled', 'disabled')], default='disabled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='type',
            field=models.CharField(choices=[('WAN', 'WAN'), ('LAN', 'LAN')], default='LAN', max_length=3, verbose_name='Type'),
        ),
    ]
