# Generated by Django 2.1.3 on 2019-01-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0035_auto_20181210_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateconfig',
            name='is_automatic_update_enabled',
        ),
        migrations.AddField(
            model_name='updateconfig',
            name='is_update_enabled',
            field=models.BooleanField(default=False, verbose_name='Update status'),
        ),
    ]
