# Generated by Django 2.1.3 on 2019-01-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0036_auto_20190106_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logserverconfig',
            name='is_secure',
        ),
        migrations.AddField(
            model_name='logserver',
            name='is_secure',
            field=models.BooleanField(default=False, verbose_name='Secure'),
        ),
    ]
