# Generated by Django 2.1.3 on 2019-01-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0037_auto_20190120_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpserverconfig',
            name='last_operation',
            field=models.CharField(blank=True, choices=[('add', 'add'), ('delete', 'delete'), ('update', 'update')],
                                   max_length=20, null=True, verbose_name='Last Operation'),
        ),
        migrations.AddField(
            model_name='dhcpserverconfig',
            name='status',
            field=models.CharField(blank=True,
                                   choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded'),
                                            ('disabled', 'disabled')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='dhcpserverconfig',
            name='subnet_mask',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Subnet mask'),
        ),
        migrations.AlterField(
            model_name='dhcpserverconfig',
            name='end_ip',
            field=models.GenericIPAddressField(verbose_name='End IP address'),
        ),
        migrations.AlterField(
            model_name='dhcpserverconfig',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.Interface'),
        ),
        migrations.AlterField(
            model_name='dhcpserverconfig',
            name='start_ip',
            field=models.GenericIPAddressField(verbose_name='Start IP address'),
        ),
    ]
