# Generated by Django 2.1.3 on 2019-02-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0038_auto_20190130_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcpserverconfig',
            name='subnet_mask',
        ),
        migrations.AddField(
            model_name='dhcpserverconfig',
            name='subnet_mask',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Subnet mask'),
        ),
    ]
