# Generated by Django 2.1.3 on 2019-03-10 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0039_auto_20190202_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='interface',
            name='mode',
            field=models.CharField(choices=[('interface', 'interface'), ('bridge', 'bridge'), ('vlan', 'vlan')],
                                   default='interface', max_length=10, verbose_name='Mode'),
        ),
    ]
