# Generated by Django 2.1.3 on 2019-03-11 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0040_auto_20190310_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(max_length=10, unique=True, validators=[
                django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$',
                                                      'Only alphanumeric characters are allowed.')],
                                   verbose_name='Name'),
        ),
    ]
