# Generated by Django 2.1.3 on 2019-03-16 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0041_auto_20190311_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='alias',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[
                django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$',
                                                      'Only alphanumeric characters are allowed.')],
                                   verbose_name='Alias'),
        ),
    ]
