# Generated by Django 2.1.3 on 2019-06-26 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0046_auto_20190518_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpserverconfig',
            name='lease_time',
            field=models.PositiveIntegerField(default=72, validators=[django.core.validators.MinValueValidator(2),
                                                                      django.core.validators.MaxValueValidator(1000)],
                                              verbose_name='Lease time'),
        ),
    ]
