# Generated by Django 2.1.3 on 2019-09-30 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config_app', '0048_interface_name_sort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogServerConfig',
        ),
    ]
