# Generated by Django 2.1.3 on 2019-09-16 15:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PKI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='data')),
                ('default_local_ca', models.BooleanField(default=False)),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='private key')),
                ('certificate', models.TextField(blank=True, null=True, verbose_name='certificate')),
                ('certificate_request', models.TextField(blank=True, null=True, verbose_name='certificate request')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('type', models.CharField(
                    choices=[('certificate', 'certificate'), ('certificate_request', 'certificate_request'),
                             ('local_certificate_authority', 'local_certificate_authority')], max_length=20,
                    verbose_name='Type')),
                ('last_operation',
                 models.CharField(blank=True, choices=[('add', 'add'), ('delete', 'delete'), ('update', 'update')],
                                  max_length=20, null=True, verbose_name='Last Operation')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('failed', 'failed'),
                                                                 ('succeeded', 'succeeded'), ('disabled', 'disabled')],
                                            max_length=20, null=True, verbose_name='Status')),
            ],
        ),
    ]
