# Generated by Django 2.1.3 on 2019-09-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pki',
            name='type',
            field=models.CharField(
                choices=[('certificate', 'certificate'), ('certificate_request', 'certificate_request'),
                         ('local_certificate_authority', 'local_certificate_authority')], max_length=30,
                verbose_name='Type'),
        ),
    ]
