# Generated by Django 2.1.3 on 2019-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pki_app', '0002_auto_20190917_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pki',
            name='certificate',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='pki',
            name='certificate_request',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='certificate request'),
        ),
        migrations.AlterField(
            model_name='pki',
            name='private_key',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='private key'),
        ),
    ]
