# Generated by Django 3.1 on 2020-08-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200802_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='extra_url',
            field=models.URLField(default=' http://192.168.203.139', max_length=250),
        ),
    ]
