# Generated by Django 2.0.3 on 2018-04-10 07:33

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[
                    django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$',
                                                          'Only alphanumeric characters are allowed.')],
                                          verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('mac', 'MAC Address'), ('fqdn', 'FQDN')],
                                          max_length=4, verbose_name='Type')),
                ('value_list',
                 django.contrib.postgres.fields.jsonb.JSONField(unique=True, verbose_name='List of addresses')),
                ('is_user_defined', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[
                    django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$',
                                                          'Only alphanumeric characters are allowed.')],
                                          verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_user_defined', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[
                    django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$',
                                                          'Only alphanumeric characters are allowed.')],
                                          verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('days_of_week', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Days of week')),
                ('is_user_defined', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[
                    django.core.validators.RegexValidator('^[0-9a-zA-Z\\,_.-]*$',
                                                          'Only alphanumeric characters are allowed.')],
                                          verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Description')),
                ('protocol',
                 models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], max_length=100, verbose_name='Protocol')),
                ('src_port_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True,
                                                                                 verbose_name='List of source ports')),
                ('dst_port_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True,
                                                                                 verbose_name='List of destination ports')),
                ('is_user_defined', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('src_port_list', 'dst_port_list', 'protocol')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('start_date', 'end_date', 'start_time', 'end_time', 'days_of_week')},
        ),
    ]
