# Generated by Django 2.0.4 on 2018-04-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entity_app', '0002_auto_20180422_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='protocol',
            field=models.CharField(default='tcp', max_length=100, verbose_name='Protocol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='protocol',
            field=models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], max_length=100, verbose_name='Protocol'),
        ),
    ]
