# Generated by Django 2.0.4 on 2018-04-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entity_app', '0003_auto_20180422_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='protocol',
            field=models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP')], max_length=100,
                                   verbose_name='Protocol'),
        ),
    ]
