# Generated by Django 2.0.6 on 2018-06-26 11:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entity_app', '0004_auto_20180422_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='protocol',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Protocol'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='service',
            name='dst_port_list',
        ),
        migrations.RemoveField(
            model_name='service',
            name='src_port_list',
        ),
    ]
