# Generated by Django 3.1 on 2020-08-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceManagement',
            new_name='Device',
        ),
    ]
