# Generated by Django 3.1 on 2020-08-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0006_auto_20200812_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('enabled', 'enabled'), ('disabled', 'disabled'), ('stopped', 'stopped')], max_length=20, verbose_name='Status'),
        ),
    ]
