# Generated by Django 3.1 on 2020-08-16 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0007_auto_20200816_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only positive numbers are allowed.')], verbose_name='Port'),
        ),
    ]
