# Generated by Django 3.1 on 2020-08-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0008_auto_20200816_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='url',
            field=models.URLField(default='http;//192.168.203.139', max_length=250),
        ),
    ]
