# Generated by Django 2.0.5 on 2018-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='mode',
            field=models.CharField(blank=True, choices=[('server', 'Server'), ('client', 'Client')], max_length=20,
                                   null=True, verbose_name='VTUN Mode'),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='type',
            field=models.CharField(choices=[('gre', 'GRE'), ('ipip', 'IPIP'), ('vtun', 'VTUN')], max_length=20,
                                   verbose_name='Encapsulation Type'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='phase1_authentication_algorithm',
            field=models.CharField(
                choices=[('md5', 'MD5'), ('md5-128', 'MD5-128'), ('sha-1', 'SHA-1'), ('sha-256', 'SHA-256')],
                max_length=20, verbose_name='Phase1 Authentication Algorithm'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='phase1_encryption_algorithm',
            field=models.CharField(
                choices=[('paya256', 'PAYA-256'), ('3des', '3DES'), ('aes128', 'AES-128'), ('aes192', 'AES-192'),
                         ('aes256', 'AES-256')], max_length=20, verbose_name='Phase1 Encryption Algorithm'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='phase2_authentication_algorithm',
            field=models.CharField(
                choices=[('md5', 'MD5'), ('md5-128', 'MD5-128'), ('sha-1', 'SHA-1'), ('sha-256', 'SHA-256')],
                max_length=20, verbose_name='Phase2 Authentication Algorithm'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='phase2_encryption_algorithm',
            field=models.CharField(
                choices=[('paya256', 'PAYA-256'), ('3des', '3DES'), ('aes128', 'AES-128'), ('aes192', 'AES-192'),
                         ('aes256', 'AES-256')], max_length=20, verbose_name='Phase2 Encryption Algorithm'),
        ),
    ]
