# Generated by Django 2.0.6 on 2018-07-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn_app', '0002_auto_20180522_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='phase1_authentication_algorithm',
            field=models.CharField(
                choices=[('md5', 'MD5'), ('md5_128', 'md5_128'), ('sha1', 'sha1'), ('sha256', 'sha256')], max_length=20,
                verbose_name='Phase1 Authentication Algorithm'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='phase2_authentication_algorithm',
            field=models.CharField(
                choices=[('md5', 'MD5'), ('md5_128', 'md5_128'), ('sha1', 'sha1'), ('sha256', 'sha256')], max_length=20,
                verbose_name='Phase2 Authentication Algorithm'),
        ),
    ]
