# Generated by Django 2.1 on 2018-08-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('entity_app', '0005_auto_20180626_1607'),
        ('vpn_app', '0004_auto_20180812_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='real_local_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='real_remote_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='server_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='virtual_local_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
        migrations.AddField(
            model_name='tunnel',
            name='virtual_remote_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
        migrations.AddField(
            model_name='vpn',
            name='local_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
        migrations.AddField(
            model_name='vpn',
            name='remote_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
    ]
