# Generated by Django 2.1 on 2018-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn_app', '0007_auto_20180903_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='is_on_demand',
            field=models.BooleanField(default=False, verbose_name='on demand'),
        ),
    ]
