# Generated by Django 2.1.3 on 2019-08-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entity_app', '0005_auto_20180626_1607'),
        ('vpn_app', '0010_auto_20190119_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='is_backup_enabled',
            field=models.BooleanField(default=False, verbose_name='Backup tunnel'),
        ),
        migrations.AddField(
            model_name='vpn',
            name='local_endpoint_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
        migrations.AddField(
            model_name='vpn',
            name='remote_endpoint_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='entity_app.Address'),
        ),
    ]
