# Generated by Django 2.0.3 on 2018-04-10 07:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source',
                 models.CharField(choices=[('policy', 'policy'), ('vpn', 'vpn'), ('service', 'service')], max_length=15,
                                  verbose_name='Source')),
                ('item', models.CharField(max_length=20, verbose_name='Item')),
                ('message', models.TextField(max_length=300, verbose_name='Message')),
                ('details',
                 django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Detail')),
                (
                'severity', models.CharField(choices=[('w', 'warning'), ('i', 'info'), ('e', 'error')], max_length=10)),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('has_seen', models.BooleanField(default=False, verbose_name='Has Seen')),
                ('user', models.CharField(default='system', max_length=30, verbose_name='User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('source', 'item')},
        ),
    ]
