# Generated by Django 2.0.5 on 2018-05-13 05:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('report_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='item',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Item'),
        ),
    ]
