# Generated by Django 2.0.5 on 2018-05-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report_app', '0002_auto_20180513_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(
                choices=[('interface', 'interface'), ('static_route', 'static_route'), ('policy', 'policy'),
                         ('vpn', 'vpn'), ('service', 'service')], max_length=15, verbose_name='Source'),
        ),
    ]
