# Generated by Django 2.0.6 on 2018-06-02 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('report_app', '0003_auto_20180523_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
    ]
