# Generated by Django 2.1.3 on 2019-02-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report_app', '0004_auto_20180602_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='Is Deletable'),
        ),
    ]
