# Generated by Django 2.1.3 on 2019-05-20 16:49

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_version', models.CharField(max_length=20, unique=True)),
                ('file', models.FileField(blank=True, null=True,
                                          storage=django.core.files.storage.FileSystemStorage(location='/var/ngfw'),
                                          upload_to='', validators=[
                        django.core.validators.FileExtensionValidator(allowed_extensions=['xz'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready')], default='pending',
                                            max_length=10)),
                ('key', models.FileField(blank=True, null=True,
                                         storage=django.core.files.storage.FileSystemStorage(location='/var/ngfw'),
                                         upload_to='', validators=[
                        django.core.validators.FileExtensionValidator(allowed_extensions=['key'])])),
            ],
        ),
    ]
