# Generated by Django 3.1 on 2020-09-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0002_auto_20200824_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='url',
        ),
        migrations.AddField(
            model_name='device',
            name='Description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description'),
        ),
    ]
