# Generated by Django 2.1.3 on 2019-04-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_input_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfirewall',
            name='protocol',
            field=models.CharField(blank=True, choices=[('udp', 'udp'), ('tcp', 'tcp')], max_length=4, null=True,
                                   verbose_name='protocol'),
        ),
    ]
