# Generated by Django 2.1.3 on 2019-04-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_input_app', '0003_apply_unapplied_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('succeeded', 'succeeded')],
                                   default='pending', max_length=10),
        ),
    ]
