# Generated by Django 2.1.3 on 2019-05-11 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_input_app', '0004_auto_20190429_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfirewall',
            name='service_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True,
                                                                                        choices=[('https', 'https'),
                                                                                                 ('ssh', 'ssh'),
                                                                                                 ('ping', 'ping'),
                                                                                                 ('ipsec', 'ipsec')],
                                                                                        max_length=10, null=True),
                                                            size=None),
        ),
    ]
