# Generated by Django 2.1.3 on 2019-05-18 10:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_input_app', '0006_auto_20190511_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfirewall',
            name='service_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True,
                                                                                        choices=[('web', 'https'),
                                                                                                 ('cli', 'ssh'),
                                                                                                 ('ping', 'ping'),
                                                                                                 ('ipsec', 'ipsec'),
                                                                                                 ('ha', 'ha'),
                                                                                                 ('dns', 'dns'),
                                                                                                 ('snmp', 'snmp'),
                                                                                                 ('ntp', 'ntp')],
                                                                                        max_length=10, null=True),
                                                            size=None),
        ),
    ]
