# Generated by Django 2.1.3 on 2019-06-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firewall_input_app', '0008_auto_20190610_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfirewall',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is enabled'),
        ),
        migrations.AlterField(
            model_name='inputfirewall',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='inputfirewall',
            name='permission',
            field=models.CharField(choices=[('admin', 'admin'), ('system', 'system'), ('hidden', 'hidden')],
                                   default='admin', max_length=10, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='inputfirewall',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='firewall_input_app.Source'),
        ),
    ]
